security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
        appliance_provider:
            entity:
                class: App\Entity\Appliance
                property: hardwareId
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        docs:
            pattern: ^/api/docs
            security: false
        
        login:
            pattern: ^/api/login
            stateless: true
            provider: user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        refresh:
            pattern: ^/api/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/refresh
                provider: user_provider
        
        api:
            pattern: ^/api
            stateless: true
            provider: appliance_provider
            user_checker: App\Security\UserChecker
            custom_authenticator: App\Security\ApplianceAuthenticator
            entry_point: jwt
            jwt:
                provider: user_provider
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/magic-login, roles: PUBLIC_ACCESS }
        - { path: ^/api/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
