security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
        appliance_provider:
            entity:
                class: App\Entity\Appliance
                property: hardwareId
        display_board_provider:
            entity:
                class: App\Entity\DisplayBoardKey
                property: key    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        docs:
            pattern: ^/api/docs
            security: false
        
        login:
            pattern: ^/api/login
            stateless: true
            provider: user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        refresh:
            pattern: ^/api/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/refresh
                provider: user_provider
                
        pictures:
            pattern: (^/api/events/(.*)/pictures$)|(^/api/pictures/(.*)/download$)
            stateless: true
            provider: display_board_provider
            custom_authenticators:
                - App\Security\ApplianceAuthenticator
                - App\Security\DisplayBoardAuthenticator
            entry_point: jwt
            jwt:
                provider: user_provider
        
        api:
            pattern: ^/api
            stateless: true
            provider: appliance_provider
            user_checker: App\Security\UserChecker
            custom_authenticator: App\Security\ApplianceAuthenticator
            entry_point: jwt
            jwt:
                provider: user_provider
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_EVENT_MAKER
        ROLE_EVENT_MAKER: ROLE_USER
    
    access_control:
        - { path: ^/api/song_formats, roles: PUBLIC_ACCESS} # TEMP
        - { path: ^/api/_sentry-test, roles: PUBLIC_ACCESS}
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/forgotten_passwords/(.*)/is-valid, roles: PUBLIC_ACCESS }
        - { path: ^/api/forgotten_passwords/(.*)/set-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/external, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
