when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            release: 'v%PARTYNEXUS_VERSION%'
            environment: '%env(SENTRY_ENV)%'
            send_default_pii: true
            max_request_body_size: always
            
            ignore_exceptions:
                - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                - Symfony\Component\Security\Core\Exception\AccessDeniedException
                - Symfony\Component\Console\Exception\*
