/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgottenPasswordIndexRouteImport } from './routes/forgotten-password/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ForgottenPasswordIdRouteImport } from './routes/forgotten-password/$id'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedIdRouteRouteImport } from './routes/_authenticated/$id/route'
import { Route as AuthenticatedKaraokeIndexRouteImport } from './routes/_authenticated/karaoke/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedIdIndexRouteImport } from './routes/_authenticated/$id/index'
import { Route as DisplayBoardEventIdKeyRouteImport } from './routes/display-board.$eventId.$key'
import { Route as AuthenticatedKaraokeRequestRouteImport } from './routes/_authenticated/karaoke/request'
import { Route as AuthenticatedKaraokeNewRouteImport } from './routes/_authenticated/karaoke/new'
import { Route as AuthenticatedKaraokeIdRouteImport } from './routes/_authenticated/karaoke/$id'
import { Route as AuthenticatedAccountChangePasswordRouteImport } from './routes/_authenticated/account/change-password'
import { Route as AuthenticatedIdTimelapseRouteImport } from './routes/_authenticated/$id/timelapse'
import { Route as AuthenticatedIdSongsRouteImport } from './routes/_authenticated/$id/songs'
import { Route as AuthenticatedIdSettingsRouteImport } from './routes/_authenticated/$id/settings'
import { Route as AuthenticatedIdPhotosRouteImport } from './routes/_authenticated/$id/photos'
import { Route as AuthenticatedIdParticipantsRouteImport } from './routes/_authenticated/$id/participants'
import { Route as AuthenticatedIdEditRouteImport } from './routes/_authenticated/$id/edit'
import { Route as AuthenticatedAccountAppliancesRouteRouteImport } from './routes/_authenticated/account/appliances/route'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminBackdropAlbumsIndexRouteImport } from './routes/_authenticated/admin/backdrop-albums/index'
import { Route as AuthenticatedAccountAppliancesIndexRouteImport } from './routes/_authenticated/account/appliances/index'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin/users/new'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminBackdropAlbumsNewRouteImport } from './routes/_authenticated/admin/backdrop-albums/new'
import { Route as AuthenticatedAdminBackdropAlbumsIdRouteImport } from './routes/_authenticated/admin/backdrop-albums/$id'
import { Route as AuthenticatedAccountAppliancesNewRouteImport } from './routes/_authenticated/account/appliances/new'
import { Route as AuthenticatedAccountAppliancesIdRouteImport } from './routes/_authenticated/account/appliances/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgottenPasswordIndexRoute = ForgottenPasswordIndexRouteImport.update({
  id: '/forgotten-password/',
  path: '/forgotten-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForgottenPasswordIdRoute = ForgottenPasswordIdRouteImport.update({
  id: '/forgotten-password/$id',
  path: '/forgotten-password/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdRouteRoute = AuthenticatedIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaraokeIndexRoute =
  AuthenticatedKaraokeIndexRouteImport.update({
    id: '/karaoke/',
    path: '/karaoke/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdIndexRoute = AuthenticatedIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedIdRouteRoute,
} as any)
const DisplayBoardEventIdKeyRoute = DisplayBoardEventIdKeyRouteImport.update({
  id: '/display-board/$eventId/$key',
  path: '/display-board/$eventId/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKaraokeRequestRoute =
  AuthenticatedKaraokeRequestRouteImport.update({
    id: '/karaoke/request',
    path: '/karaoke/request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaraokeNewRoute = AuthenticatedKaraokeNewRouteImport.update({
  id: '/karaoke/new',
  path: '/karaoke/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaraokeIdRoute = AuthenticatedKaraokeIdRouteImport.update({
  id: '/karaoke/$id',
  path: '/karaoke/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountChangePasswordRoute =
  AuthenticatedAccountChangePasswordRouteImport.update({
    id: '/account/change-password',
    path: '/account/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdTimelapseRoute =
  AuthenticatedIdTimelapseRouteImport.update({
    id: '/timelapse',
    path: '/timelapse',
    getParentRoute: () => AuthenticatedIdRouteRoute,
  } as any)
const AuthenticatedIdSongsRoute = AuthenticatedIdSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AuthenticatedIdRouteRoute,
} as any)
const AuthenticatedIdSettingsRoute = AuthenticatedIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedIdRouteRoute,
} as any)
const AuthenticatedIdPhotosRoute = AuthenticatedIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedIdRouteRoute,
} as any)
const AuthenticatedIdParticipantsRoute =
  AuthenticatedIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedIdRouteRoute,
  } as any)
const AuthenticatedIdEditRoute = AuthenticatedIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedIdRouteRoute,
} as any)
const AuthenticatedAccountAppliancesRouteRoute =
  AuthenticatedAccountAppliancesRouteRouteImport.update({
    id: '/account/appliances',
    path: '/account/appliances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackdropAlbumsIndexRoute =
  AuthenticatedAdminBackdropAlbumsIndexRouteImport.update({
    id: '/backdrop-albums/',
    path: '/backdrop-albums/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAccountAppliancesIndexRoute =
  AuthenticatedAccountAppliancesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountAppliancesRouteRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/users/new',
    path: '/users/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackdropAlbumsNewRoute =
  AuthenticatedAdminBackdropAlbumsNewRouteImport.update({
    id: '/backdrop-albums/new',
    path: '/backdrop-albums/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackdropAlbumsIdRoute =
  AuthenticatedAdminBackdropAlbumsIdRouteImport.update({
    id: '/backdrop-albums/$id',
    path: '/backdrop-albums/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAccountAppliancesNewRoute =
  AuthenticatedAccountAppliancesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountAppliancesRouteRoute,
  } as any)
const AuthenticatedAccountAppliancesIdRoute =
  AuthenticatedAccountAppliancesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAccountAppliancesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$id': typeof AuthenticatedIdRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/forgotten-password/$id': typeof ForgottenPasswordIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/forgotten-password': typeof ForgottenPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/account/appliances': typeof AuthenticatedAccountAppliancesRouteRouteWithChildren
  '/$id/edit': typeof AuthenticatedIdEditRoute
  '/$id/participants': typeof AuthenticatedIdParticipantsRoute
  '/$id/photos': typeof AuthenticatedIdPhotosRoute
  '/$id/settings': typeof AuthenticatedIdSettingsRoute
  '/$id/songs': typeof AuthenticatedIdSongsRoute
  '/$id/timelapse': typeof AuthenticatedIdTimelapseRoute
  '/account/change-password': typeof AuthenticatedAccountChangePasswordRoute
  '/karaoke/$id': typeof AuthenticatedKaraokeIdRoute
  '/karaoke/new': typeof AuthenticatedKaraokeNewRoute
  '/karaoke/request': typeof AuthenticatedKaraokeRequestRoute
  '/display-board/$eventId/$key': typeof DisplayBoardEventIdKeyRoute
  '/$id/': typeof AuthenticatedIdIndexRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/karaoke': typeof AuthenticatedKaraokeIndexRoute
  '/account/appliances/$id': typeof AuthenticatedAccountAppliancesIdRoute
  '/account/appliances/new': typeof AuthenticatedAccountAppliancesNewRoute
  '/admin/backdrop-albums/$id': typeof AuthenticatedAdminBackdropAlbumsIdRoute
  '/admin/backdrop-albums/new': typeof AuthenticatedAdminBackdropAlbumsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/account/appliances/': typeof AuthenticatedAccountAppliancesIndexRoute
  '/admin/backdrop-albums': typeof AuthenticatedAdminBackdropAlbumsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/new': typeof AuthenticatedNewRoute
  '/forgotten-password/$id': typeof ForgottenPasswordIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/forgotten-password': typeof ForgottenPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/$id/edit': typeof AuthenticatedIdEditRoute
  '/$id/participants': typeof AuthenticatedIdParticipantsRoute
  '/$id/photos': typeof AuthenticatedIdPhotosRoute
  '/$id/settings': typeof AuthenticatedIdSettingsRoute
  '/$id/songs': typeof AuthenticatedIdSongsRoute
  '/$id/timelapse': typeof AuthenticatedIdTimelapseRoute
  '/account/change-password': typeof AuthenticatedAccountChangePasswordRoute
  '/karaoke/$id': typeof AuthenticatedKaraokeIdRoute
  '/karaoke/new': typeof AuthenticatedKaraokeNewRoute
  '/karaoke/request': typeof AuthenticatedKaraokeRequestRoute
  '/display-board/$eventId/$key': typeof DisplayBoardEventIdKeyRoute
  '/$id': typeof AuthenticatedIdIndexRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/karaoke': typeof AuthenticatedKaraokeIndexRoute
  '/account/appliances/$id': typeof AuthenticatedAccountAppliancesIdRoute
  '/account/appliances/new': typeof AuthenticatedAccountAppliancesNewRoute
  '/admin/backdrop-albums/$id': typeof AuthenticatedAdminBackdropAlbumsIdRoute
  '/admin/backdrop-albums/new': typeof AuthenticatedAdminBackdropAlbumsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/account/appliances': typeof AuthenticatedAccountAppliancesIndexRoute
  '/admin/backdrop-albums': typeof AuthenticatedAdminBackdropAlbumsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$id': typeof AuthenticatedIdRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/forgotten-password/$id': typeof ForgottenPasswordIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forgotten-password/': typeof ForgottenPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/account/appliances': typeof AuthenticatedAccountAppliancesRouteRouteWithChildren
  '/_authenticated/$id/edit': typeof AuthenticatedIdEditRoute
  '/_authenticated/$id/participants': typeof AuthenticatedIdParticipantsRoute
  '/_authenticated/$id/photos': typeof AuthenticatedIdPhotosRoute
  '/_authenticated/$id/settings': typeof AuthenticatedIdSettingsRoute
  '/_authenticated/$id/songs': typeof AuthenticatedIdSongsRoute
  '/_authenticated/$id/timelapse': typeof AuthenticatedIdTimelapseRoute
  '/_authenticated/account/change-password': typeof AuthenticatedAccountChangePasswordRoute
  '/_authenticated/karaoke/$id': typeof AuthenticatedKaraokeIdRoute
  '/_authenticated/karaoke/new': typeof AuthenticatedKaraokeNewRoute
  '/_authenticated/karaoke/request': typeof AuthenticatedKaraokeRequestRoute
  '/display-board/$eventId/$key': typeof DisplayBoardEventIdKeyRoute
  '/_authenticated/$id/': typeof AuthenticatedIdIndexRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/karaoke/': typeof AuthenticatedKaraokeIndexRoute
  '/_authenticated/account/appliances/$id': typeof AuthenticatedAccountAppliancesIdRoute
  '/_authenticated/account/appliances/new': typeof AuthenticatedAccountAppliancesNewRoute
  '/_authenticated/admin/backdrop-albums/$id': typeof AuthenticatedAdminBackdropAlbumsIdRoute
  '/_authenticated/admin/backdrop-albums/new': typeof AuthenticatedAdminBackdropAlbumsNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/account/appliances/': typeof AuthenticatedAccountAppliancesIndexRoute
  '/_authenticated/admin/backdrop-albums/': typeof AuthenticatedAdminBackdropAlbumsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$id'
    | '/admin'
    | '/new'
    | '/forgotten-password/$id'
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/account/appliances'
    | '/$id/edit'
    | '/$id/participants'
    | '/$id/photos'
    | '/$id/settings'
    | '/$id/songs'
    | '/$id/timelapse'
    | '/account/change-password'
    | '/karaoke/$id'
    | '/karaoke/new'
    | '/karaoke/request'
    | '/display-board/$eventId/$key'
    | '/$id/'
    | '/account'
    | '/admin/'
    | '/karaoke'
    | '/account/appliances/$id'
    | '/account/appliances/new'
    | '/admin/backdrop-albums/$id'
    | '/admin/backdrop-albums/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/account/appliances/'
    | '/admin/backdrop-albums'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/new'
    | '/forgotten-password/$id'
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/$id/edit'
    | '/$id/participants'
    | '/$id/photos'
    | '/$id/settings'
    | '/$id/songs'
    | '/$id/timelapse'
    | '/account/change-password'
    | '/karaoke/$id'
    | '/karaoke/new'
    | '/karaoke/request'
    | '/display-board/$eventId/$key'
    | '/$id'
    | '/account'
    | '/admin'
    | '/karaoke'
    | '/account/appliances/$id'
    | '/account/appliances/new'
    | '/admin/backdrop-albums/$id'
    | '/admin/backdrop-albums/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/account/appliances'
    | '/admin/backdrop-albums'
    | '/admin/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$id'
    | '/_authenticated/admin'
    | '/_authenticated/new'
    | '/forgotten-password/$id'
    | '/_authenticated/'
    | '/forgotten-password/'
    | '/login/'
    | '/_authenticated/account/appliances'
    | '/_authenticated/$id/edit'
    | '/_authenticated/$id/participants'
    | '/_authenticated/$id/photos'
    | '/_authenticated/$id/settings'
    | '/_authenticated/$id/songs'
    | '/_authenticated/$id/timelapse'
    | '/_authenticated/account/change-password'
    | '/_authenticated/karaoke/$id'
    | '/_authenticated/karaoke/new'
    | '/_authenticated/karaoke/request'
    | '/display-board/$eventId/$key'
    | '/_authenticated/$id/'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/karaoke/'
    | '/_authenticated/account/appliances/$id'
    | '/_authenticated/account/appliances/new'
    | '/_authenticated/admin/backdrop-albums/$id'
    | '/_authenticated/admin/backdrop-albums/new'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/account/appliances/'
    | '/_authenticated/admin/backdrop-albums/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgottenPasswordIdRoute: typeof ForgottenPasswordIdRoute
  ForgottenPasswordIndexRoute: typeof ForgottenPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  DisplayBoardEventIdKeyRoute: typeof DisplayBoardEventIdKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotten-password/': {
      id: '/forgotten-password/'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof ForgottenPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forgotten-password/$id': {
      id: '/forgotten-password/$id'
      path: '/forgotten-password/$id'
      fullPath: '/forgotten-password/$id'
      preLoaderRoute: typeof ForgottenPasswordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$id': {
      id: '/_authenticated/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof AuthenticatedIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karaoke/': {
      id: '/_authenticated/karaoke/'
      path: '/karaoke'
      fullPath: '/karaoke'
      preLoaderRoute: typeof AuthenticatedKaraokeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$id/': {
      id: '/_authenticated/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof AuthenticatedIdIndexRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/display-board/$eventId/$key': {
      id: '/display-board/$eventId/$key'
      path: '/display-board/$eventId/$key'
      fullPath: '/display-board/$eventId/$key'
      preLoaderRoute: typeof DisplayBoardEventIdKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/karaoke/request': {
      id: '/_authenticated/karaoke/request'
      path: '/karaoke/request'
      fullPath: '/karaoke/request'
      preLoaderRoute: typeof AuthenticatedKaraokeRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karaoke/new': {
      id: '/_authenticated/karaoke/new'
      path: '/karaoke/new'
      fullPath: '/karaoke/new'
      preLoaderRoute: typeof AuthenticatedKaraokeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karaoke/$id': {
      id: '/_authenticated/karaoke/$id'
      path: '/karaoke/$id'
      fullPath: '/karaoke/$id'
      preLoaderRoute: typeof AuthenticatedKaraokeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/change-password': {
      id: '/_authenticated/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AuthenticatedAccountChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$id/timelapse': {
      id: '/_authenticated/$id/timelapse'
      path: '/timelapse'
      fullPath: '/$id/timelapse'
      preLoaderRoute: typeof AuthenticatedIdTimelapseRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/$id/songs': {
      id: '/_authenticated/$id/songs'
      path: '/songs'
      fullPath: '/$id/songs'
      preLoaderRoute: typeof AuthenticatedIdSongsRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/$id/settings': {
      id: '/_authenticated/$id/settings'
      path: '/settings'
      fullPath: '/$id/settings'
      preLoaderRoute: typeof AuthenticatedIdSettingsRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/$id/photos': {
      id: '/_authenticated/$id/photos'
      path: '/photos'
      fullPath: '/$id/photos'
      preLoaderRoute: typeof AuthenticatedIdPhotosRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/$id/participants': {
      id: '/_authenticated/$id/participants'
      path: '/participants'
      fullPath: '/$id/participants'
      preLoaderRoute: typeof AuthenticatedIdParticipantsRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/$id/edit': {
      id: '/_authenticated/$id/edit'
      path: '/edit'
      fullPath: '/$id/edit'
      preLoaderRoute: typeof AuthenticatedIdEditRouteImport
      parentRoute: typeof AuthenticatedIdRouteRoute
    }
    '/_authenticated/account/appliances': {
      id: '/_authenticated/account/appliances'
      path: '/account/appliances'
      fullPath: '/account/appliances'
      preLoaderRoute: typeof AuthenticatedAccountAppliancesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backdrop-albums/': {
      id: '/_authenticated/admin/backdrop-albums/'
      path: '/backdrop-albums'
      fullPath: '/admin/backdrop-albums'
      preLoaderRoute: typeof AuthenticatedAdminBackdropAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/appliances/': {
      id: '/_authenticated/account/appliances/'
      path: '/'
      fullPath: '/account/appliances/'
      preLoaderRoute: typeof AuthenticatedAccountAppliancesIndexRouteImport
      parentRoute: typeof AuthenticatedAccountAppliancesRouteRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backdrop-albums/new': {
      id: '/_authenticated/admin/backdrop-albums/new'
      path: '/backdrop-albums/new'
      fullPath: '/admin/backdrop-albums/new'
      preLoaderRoute: typeof AuthenticatedAdminBackdropAlbumsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backdrop-albums/$id': {
      id: '/_authenticated/admin/backdrop-albums/$id'
      path: '/backdrop-albums/$id'
      fullPath: '/admin/backdrop-albums/$id'
      preLoaderRoute: typeof AuthenticatedAdminBackdropAlbumsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/appliances/new': {
      id: '/_authenticated/account/appliances/new'
      path: '/new'
      fullPath: '/account/appliances/new'
      preLoaderRoute: typeof AuthenticatedAccountAppliancesNewRouteImport
      parentRoute: typeof AuthenticatedAccountAppliancesRouteRoute
    }
    '/_authenticated/account/appliances/$id': {
      id: '/_authenticated/account/appliances/$id'
      path: '/$id'
      fullPath: '/account/appliances/$id'
      preLoaderRoute: typeof AuthenticatedAccountAppliancesIdRouteImport
      parentRoute: typeof AuthenticatedAccountAppliancesRouteRoute
    }
  }
}

interface AuthenticatedIdRouteRouteChildren {
  AuthenticatedIdEditRoute: typeof AuthenticatedIdEditRoute
  AuthenticatedIdParticipantsRoute: typeof AuthenticatedIdParticipantsRoute
  AuthenticatedIdPhotosRoute: typeof AuthenticatedIdPhotosRoute
  AuthenticatedIdSettingsRoute: typeof AuthenticatedIdSettingsRoute
  AuthenticatedIdSongsRoute: typeof AuthenticatedIdSongsRoute
  AuthenticatedIdTimelapseRoute: typeof AuthenticatedIdTimelapseRoute
  AuthenticatedIdIndexRoute: typeof AuthenticatedIdIndexRoute
}

const AuthenticatedIdRouteRouteChildren: AuthenticatedIdRouteRouteChildren = {
  AuthenticatedIdEditRoute: AuthenticatedIdEditRoute,
  AuthenticatedIdParticipantsRoute: AuthenticatedIdParticipantsRoute,
  AuthenticatedIdPhotosRoute: AuthenticatedIdPhotosRoute,
  AuthenticatedIdSettingsRoute: AuthenticatedIdSettingsRoute,
  AuthenticatedIdSongsRoute: AuthenticatedIdSongsRoute,
  AuthenticatedIdTimelapseRoute: AuthenticatedIdTimelapseRoute,
  AuthenticatedIdIndexRoute: AuthenticatedIdIndexRoute,
}

const AuthenticatedIdRouteRouteWithChildren =
  AuthenticatedIdRouteRoute._addFileChildren(AuthenticatedIdRouteRouteChildren)

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBackdropAlbumsIdRoute: typeof AuthenticatedAdminBackdropAlbumsIdRoute
  AuthenticatedAdminBackdropAlbumsNewRoute: typeof AuthenticatedAdminBackdropAlbumsNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
  AuthenticatedAdminBackdropAlbumsIndexRoute: typeof AuthenticatedAdminBackdropAlbumsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminBackdropAlbumsIdRoute:
      AuthenticatedAdminBackdropAlbumsIdRoute,
    AuthenticatedAdminBackdropAlbumsNewRoute:
      AuthenticatedAdminBackdropAlbumsNewRoute,
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
    AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
    AuthenticatedAdminBackdropAlbumsIndexRoute:
      AuthenticatedAdminBackdropAlbumsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAccountAppliancesRouteRouteChildren {
  AuthenticatedAccountAppliancesIdRoute: typeof AuthenticatedAccountAppliancesIdRoute
  AuthenticatedAccountAppliancesNewRoute: typeof AuthenticatedAccountAppliancesNewRoute
  AuthenticatedAccountAppliancesIndexRoute: typeof AuthenticatedAccountAppliancesIndexRoute
}

const AuthenticatedAccountAppliancesRouteRouteChildren: AuthenticatedAccountAppliancesRouteRouteChildren =
  {
    AuthenticatedAccountAppliancesIdRoute:
      AuthenticatedAccountAppliancesIdRoute,
    AuthenticatedAccountAppliancesNewRoute:
      AuthenticatedAccountAppliancesNewRoute,
    AuthenticatedAccountAppliancesIndexRoute:
      AuthenticatedAccountAppliancesIndexRoute,
  }

const AuthenticatedAccountAppliancesRouteRouteWithChildren =
  AuthenticatedAccountAppliancesRouteRoute._addFileChildren(
    AuthenticatedAccountAppliancesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIdRouteRoute: typeof AuthenticatedIdRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountAppliancesRouteRoute: typeof AuthenticatedAccountAppliancesRouteRouteWithChildren
  AuthenticatedAccountChangePasswordRoute: typeof AuthenticatedAccountChangePasswordRoute
  AuthenticatedKaraokeIdRoute: typeof AuthenticatedKaraokeIdRoute
  AuthenticatedKaraokeNewRoute: typeof AuthenticatedKaraokeNewRoute
  AuthenticatedKaraokeRequestRoute: typeof AuthenticatedKaraokeRequestRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedKaraokeIndexRoute: typeof AuthenticatedKaraokeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIdRouteRoute: AuthenticatedIdRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountAppliancesRouteRoute:
    AuthenticatedAccountAppliancesRouteRouteWithChildren,
  AuthenticatedAccountChangePasswordRoute:
    AuthenticatedAccountChangePasswordRoute,
  AuthenticatedKaraokeIdRoute: AuthenticatedKaraokeIdRoute,
  AuthenticatedKaraokeNewRoute: AuthenticatedKaraokeNewRoute,
  AuthenticatedKaraokeRequestRoute: AuthenticatedKaraokeRequestRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedKaraokeIndexRoute: AuthenticatedKaraokeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgottenPasswordIdRoute: ForgottenPasswordIdRoute,
  ForgottenPasswordIndexRoute: ForgottenPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  DisplayBoardEventIdKeyRoute: DisplayBoardEventIdKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
